title: "SINTRASPAP"
description: "Sindicato Nacional de Trabajadores de la Seguridad Privada y Afines del Paraguay"
theme: minima

url: "https://sintraspappy2025.github.io"
baseurl: ""

permalink: /:year/:month/:day/:title/
